#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import pathlib


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
SPRITE_COLOR_PATH = REPO_ROOT / "assets" / "sprite_colors.bin"
OUTPUT_PATH = REPO_ROOT / "src" / "sprite_review_shadow.inc"
SUMMARY_PATH = REPO_ROOT / "assets" / "sprite_review_shadow_summary.txt"

SPRITE_SAT_SHADOW = 0x8300
SPRITE_COLOR_SHADOW = 0x8330
SPRITE_COLOR_STRIDE = 16

SPRITES = [
    {
        "slot": 0,
        "name": "Pac-Man",
        "state": "normal mouth frame",
        "x": 56,
        "y": 96,
        "sprite_id": 1,
        "pattern": 1 * 4,
        "palette": 1,
    },
    {
        "slot": 1,
        "name": "Blinky",
        "state": "normal chase outside",
        "x": 88,
        "y": 96,
        "sprite_id": 8,
        "pattern": 8 * 4,
        "palette": 2,
    },
    {
        "slot": 2,
        "name": "Pinky",
        "state": "frightened outside",
        "x": 120,
        "y": 96,
        "sprite_id": 50,
        "pattern": 50 * 4,
        "palette": 8,
    },
    {
        "slot": 3,
        "name": "Inky",
        "state": "house waiting",
        "x": 152,
        "y": 96,
        "sprite_id": 32,
        "pattern": 32 * 4,
        "palette": 4,
    },
    {
        "slot": 4,
        "name": "Clyde",
        "state": "house exiting",
        "x": 184,
        "y": 96,
        "sprite_id": 9,
        "pattern": 9 * 4,
        "palette": 5,
    },
]


def load_source_colors(path: pathlib.Path) -> bytes:
    data = path.read_bytes()
    if len(data) != 1024:
        raise ValueError(f"{path.relative_to(REPO_ROOT)} must be 1024 bytes; got {len(data)}")
    return data


def overridden_rows(source_colors: bytes, sprite_id: int, palette: int) -> list[int]:
    start = sprite_id * SPRITE_COLOR_STRIDE
    source_rows = source_colors[start : start + SPRITE_COLOR_STRIDE]
    if len(source_rows) != SPRITE_COLOR_STRIDE:
        raise ValueError(f"Sprite {sprite_id} color row slice is incomplete.")
    return [0 if value == 0 else palette for value in source_rows]


def build_sat_bytes() -> list[int]:
    sat: list[int] = []
    for sprite in SPRITES:
        sat.extend([sprite["y"], sprite["x"], sprite["pattern"], sprite["palette"], 0, 0, 0, 0])
    sat.extend([0xD0, 0, 0, 0, 0, 0, 0, 0])
    return sat


def build_color_bytes(source_colors: bytes) -> list[int]:
    color_bytes: list[int] = []
    for sprite in SPRITES:
        color_bytes.extend(
            overridden_rows(source_colors, int(sprite["sprite_id"]), int(sprite["palette"]))
        )
    color_bytes.extend([0] * SPRITE_COLOR_STRIDE)
    return color_bytes


def build_review_shadow(source_colors: bytes) -> tuple[list[int], list[int]]:
    sat = build_sat_bytes()
    colors = build_color_bytes(source_colors)
    if len(sat) != 48:
        raise ValueError(f"SAT shadow must be 48 bytes; got {len(sat)}")
    if len(colors) != 96:
        raise ValueError(f"Color shadow must be 96 bytes; got {len(colors)}")
    return sat, colors


def store_lines(base: int, values: list[int]) -> list[str]:
    lines: list[str] = []
    for offset, value in enumerate(values):
        lines.append(f"        ld a, 0x{value:02X}")
        lines.append(f"        ld (0x{base + offset:04X}), a")
    return lines


def write_include(path: pathlib.Path, sat: list[int], colors: list[int]) -> None:
    lines = [
        "; Generated by tools/generate_sprite_review_shadow.py.",
        "; Source: assets/sprite_colors.bin plus deterministic T013 review slots.",
        "",
        "; Sprite Mode 2 SAT shadow at 0x8300.",
    ]
    lines.extend(store_lines(SPRITE_SAT_SHADOW, sat))
    lines.extend(["", "; Sprite Mode 2 per-slot color shadow at 0x8330."])
    lines.extend(store_lines(SPRITE_COLOR_SHADOW, colors))
    lines.append("")
    path.write_text("\n".join(lines), encoding="ascii")


def format_hex(values: list[int]) -> str:
    return " ".join(f"{value:02X}" for value in values)


def write_summary(path: pathlib.Path, source_colors: bytes, sat: list[int], colors: list[int]) -> None:
    lines = [
        "T013 sprite review shadow summary",
        f"Source colors: assets/sprite_colors.bin bytes={len(source_colors)} "
        f"sha256={hashlib.sha256(source_colors).hexdigest()}",
        f"SAT shadow bytes: {len(sat)} sha256={hashlib.sha256(bytes(sat)).hexdigest()}",
        f"Color shadow bytes: {len(colors)} sha256={hashlib.sha256(bytes(colors)).hexdigest()}",
        "",
        "Slots:",
    ]
    for sprite in SPRITES:
        slot = int(sprite["slot"])
        color_start = slot * SPRITE_COLOR_STRIDE
        lines.append(
            f"- slot {slot}: {sprite['name']} state={sprite['state']} "
            f"xy=({sprite['x']},{sprite['y']}) sprite_id={sprite['sprite_id']} "
            f"pattern={sprite['pattern']} palette={sprite['palette']} "
            f"sat={format_hex(sat[slot * 8 : slot * 8 + 8])} "
            f"colors={format_hex(colors[color_start : color_start + SPRITE_COLOR_STRIDE])}"
        )
    lines.append(f"- slot 5: reserved terminator sat={format_hex(sat[40:48])}")
    lines.append("")
    lines.append("Coordinate note: fixed T013 review positions, not final T015 transform output.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate deterministic T013 sprite SAT/color shadow include."
    )
    parser.add_argument("--output", type=pathlib.Path, default=OUTPUT_PATH)
    parser.add_argument("--summary-output", type=pathlib.Path, default=SUMMARY_PATH)
    args = parser.parse_args()

    source_colors = load_source_colors(SPRITE_COLOR_PATH)
    sat, colors = build_review_shadow(source_colors)
    write_include(args.output, sat, colors)
    write_summary(args.summary_output, source_colors, sat, colors)

    print(f"Wrote {args.output.relative_to(REPO_ROOT)}")
    print(f"Wrote {args.summary_output.relative_to(REPO_ROOT)}")
    print(f"SAT shadow SHA-256: {hashlib.sha256(bytes(sat)).hexdigest()}")
    print(f"Color shadow SHA-256: {hashlib.sha256(bytes(colors)).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
