#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import pathlib

import generate_hud_assets as hud


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
HUD_TILES_PATH = REPO_ROOT / "assets" / "hud_tiles.bin"
HUD_PATCH_PATH = REPO_ROOT / "assets" / "hud_patch.bin"
HUD_SUMMARY_PATH = REPO_ROOT / "assets" / "hud_assets_summary.txt"
HUD_DRAW_INCLUDE_PATH = REPO_ROOT / "src" / "hud_review_draw.inc"
PALETTE_A_PATH = REPO_ROOT / "assets" / "palette_a.bin"


def sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rel(path: pathlib.Path) -> pathlib.Path:
    return path.resolve().relative_to(REPO_ROOT)


def require(condition: bool, message: str, failures: list[str]) -> None:
    if not condition:
        failures.append(message)


def parse_ppm(path: pathlib.Path) -> tuple[int, int, str, bytes]:
    data = path.read_bytes()
    parts = data.split(b"\n", 3)
    if len(parts) != 4:
        raise ValueError("PPM header is incomplete.")
    magic, dimensions, max_value, body = parts
    if magic != b"P6":
        raise ValueError(f"Unexpected PPM magic {magic!r}.")
    width_text, height_text = dimensions.split()
    width = int(width_text)
    height = int(height_text)
    if max_value != b"255":
        raise ValueError(f"Unexpected PPM max value {max_value!r}.")
    expected_bytes = width * height * 3
    if len(body) != expected_bytes:
        raise ValueError(f"PPM body is {len(body)} bytes; expected {expected_bytes}.")
    return width, height, hashlib.sha256(data).hexdigest(), body


def count_nonblack_pixels(body: bytes, width: int, y_start: int, y_end: int) -> int:
    count = 0
    for y in range(y_start, y_end):
        row_start = y * width * 3
        for x in range(width):
            offset = row_start + x * 3
            if body[offset : offset + 3] != b"\x00\x00\x00":
                count += 1
    return count


def generated_outputs() -> tuple[bytes, bytes, str, str, str, int]:
    index_by_key, tiles = hud.collect_tiles()
    atlas = hud.build_atlas(tiles)
    entries = hud.sequence_entries(hud.TOP_SEQUENCE, hud.TOP_ROW_Y, index_by_key)
    entries.extend(hud.sequence_entries(hud.BOTTOM_SEQUENCE, hud.BOTTOM_ROW_Y, index_by_key))
    patch = hud.build_patch(tiles, entries)

    draw_lines = [
        "; Generated by tools/generate_hud_assets.py.",
        "; Source: deterministic T014 HUD strings and built-in 5x7/icon pixel maps.",
        "",
    ]
    for entry in entries:
        draw_lines.append(
            f"        HUD_PATCH_TILE 0x{int(entry['tile']):02X}, "
            f"0x{int(entry['x']):02X}, 0x{int(entry['y']):02X} "
            f"; {entry['key']} col={entry['col']} token={entry['char']}"
        )
    draw_lines.append("")
    return (
        atlas,
        patch,
        "\n".join(draw_lines),
        hashlib.sha256(atlas).hexdigest(),
        hashlib.sha256(patch).hexdigest(),
        len(entries),
    )


def write_vectors(
    path: pathlib.Path,
    atlas_hash: str,
    patch_hash: str,
    blit_count: int,
    frame_hash: str | None,
    frame_dimensions: tuple[int, int] | None,
    band_counts: tuple[int, int] | None,
) -> None:
    lines = [
        "T014 HUD render vectors",
        "",
        "HUD values:",
        "- top row: 1UP 000120 HIGH SCORE 001000 2UP",
        "- bottom row: LIVES with 3 life icons; FRUIT with cherry/strawberry/orange icons",
        "",
        "VRAM layout:",
        "- VDP-A HUD patch: top 0x0000 and bottom 0x6600, 1024 bytes per band",
        "- VDP-A HUD tile atlas reference: source_y=212, 1024 bytes",
        "- VDP-A framebuffer bands: top y=0..7, bottom y=204..211",
        "- CPU VRAM dirty bands: 128 bytes x 8 rows each",
        "- sprite slots: slots 0..4 owned by T013 entities; slot 5 remains reserved terminator",
        "",
        "Palette indices:",
        "- 0 transparent",
        "- 1 score/life yellow",
        "- 2 red fruit",
        "- 3 pink fruit",
        "- 6 HUD label text",
        "- 13 fruit stem green",
        "- 15 orange fruit",
        "",
        "Asset hashes:",
        f"- assets/hud_tiles.bin: {sha256(HUD_TILES_PATH)} expected={atlas_hash}",
        f"- assets/hud_patch.bin: {sha256(HUD_PATCH_PATH)} expected={patch_hash}",
        f"- src/hud_review_draw.inc: {sha256(HUD_DRAW_INCLUDE_PATH)}",
        f"- assets/hud_assets_summary.txt: {sha256(HUD_SUMMARY_PATH)}",
        f"- assets/palette_a.bin: {sha256(PALETTE_A_PATH)}",
        "",
        "Dirty regions:",
        f"- source non-space glyph/icon placements: {blit_count}",
        "- top band CPU VRAM blit: dst=(0,0), bytes=128x8",
        "- bottom band CPU VRAM blit: dst=(0,204), bytes=128x8",
    ]
    if frame_hash is not None and frame_dimensions is not None:
        lines.append(
            f"- frame dump: {frame_dimensions[0]}x{frame_dimensions[1]} sha256={frame_hash}"
        )
    if band_counts is not None:
        top_count, bottom_count = band_counts
        lines.append(f"- nonblack pixels in top 8px band: {top_count}")
        lines.append(f"- nonblack pixels in bottom 8px band: {bottom_count}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate deterministic T014 HUD render data.")
    parser.add_argument("--vectors-output", type=pathlib.Path, required=True)
    parser.add_argument("--frame-dump", type=pathlib.Path)
    args = parser.parse_args()

    failures: list[str] = []
    (
        expected_atlas,
        expected_patch,
        expected_draw,
        expected_atlas_hash,
        expected_patch_hash,
        blit_count,
    ) = generated_outputs()

    require(HUD_TILES_PATH.is_file(), "assets/hud_tiles.bin must exist", failures)
    require(HUD_PATCH_PATH.is_file(), "assets/hud_patch.bin must exist", failures)
    require(HUD_DRAW_INCLUDE_PATH.is_file(), "src/hud_review_draw.inc must exist", failures)
    require(HUD_SUMMARY_PATH.is_file(), "assets/hud_assets_summary.txt must exist", failures)
    require(PALETTE_A_PATH.stat().st_size == 32, "assets/palette_a.bin must be 32 bytes", failures)

    if HUD_TILES_PATH.is_file():
        actual_atlas = HUD_TILES_PATH.read_bytes()
        require(len(actual_atlas) == hud.ATLAS_BYTES, "HUD atlas must be 1024 bytes", failures)
        require(actual_atlas == expected_atlas, "HUD tile atlas is stale", failures)
    if HUD_PATCH_PATH.is_file():
        actual_patch = HUD_PATCH_PATH.read_bytes()
        require(len(actual_patch) == hud.PATCH_BYTES, "HUD patch must be 2048 bytes", failures)
        require(actual_patch == expected_patch, "HUD patch is stale", failures)
    if HUD_DRAW_INCLUDE_PATH.is_file():
        require(
            HUD_DRAW_INCLUDE_PATH.read_text(encoding="ascii") == expected_draw,
            "HUD draw include is stale",
            failures,
        )

    frame_hash: str | None = None
    frame_dimensions: tuple[int, int] | None = None
    band_counts: tuple[int, int] | None = None
    if args.frame_dump is not None:
        width, height, frame_hash, body = parse_ppm(args.frame_dump)
        frame_dimensions = (width, height)
        require((width, height) == (256, 212), "frame dump must be 256x212", failures)
        top_count = count_nonblack_pixels(body, width, 0, 8)
        bottom_count = count_nonblack_pixels(body, width, 204, 212)
        band_counts = (top_count, bottom_count)
        require(top_count > 150, "top HUD band must contain visible HUD pixels", failures)
        require(bottom_count > 100, "bottom HUD band must contain visible HUD pixels", failures)

    write_vectors(
        args.vectors_output,
        expected_atlas_hash,
        expected_patch_hash,
        blit_count,
        frame_hash,
        frame_dimensions,
        band_counts,
    )

    if failures:
        print("hud_render_tests: FAILED")
        for failure in failures:
            print(f"- {failure}")
        return 1

    print("hud_render_tests: 11/11 passed")
    print(f"hud_tiles.bin SHA-256: {sha256(HUD_TILES_PATH)}")
    print(f"hud_patch.bin SHA-256: {sha256(HUD_PATCH_PATH)}")
    print(f"hud_review_draw.inc SHA-256: {sha256(HUD_DRAW_INCLUDE_PATH)}")
    print(f"palette_a.bin SHA-256: {sha256(PALETTE_A_PATH)}")
    if frame_hash is not None:
        print(f"Frame dump SHA-256: {frame_hash}")
    if band_counts is not None:
        print(f"Top HUD nonblack pixels: {band_counts[0]}")
        print(f"Bottom HUD nonblack pixels: {band_counts[1]}")
    print(f"Vectors: {rel(args.vectors_output)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
